name: dbt CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Configure dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOL
          zillow_dbt:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: ZXEPCNH-CJ03437
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: "${{ secrets.SNOWFLAKE_PASSWORD }}"
                role: ACCOUNTADMIN
                warehouse: COMPUTE_WH
                database: ZILLOW_DATA
                schema: CURATED
                threads: 4
                client_session_keep_alive: false
          EOL

      - name: Debug dbt connection
        run: dbt debug

      - name: Run dbt models
        run: dbt run

      - name: Run dbt tests
        run: dbt test